### ISSUE TITLE
Dataset Annotation Fail on MyPy

### ISSUE THREAD

**Issue by gao462** [pyg-team/pytorch_geometric#4632]
### 🐛 Describe the bug

Here is my code and configuration toml file:
```python
from torch_geometric.data import InMemoryDataset

class MyDataset(InMemoryDataset):
    pass
```
```toml
# Build package.
[build-system]
requires = ["setuptools>=58.2.0", "wheel>=0.37.0"]
build-backend = "setuptools.build_meta"

# Check static typing.
[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
check_untyped_defs = false         # Default `--strict` mode. Loose it for convenience.
disallow_any_expr = false          # Extremely strict mode.
disallow_any_explicit = false      # Extremely strict mode.
disallow_any_generics = true       # Default `--strict` mode.
disallow_incomplete_defs = false   # Default `--strict` mode. Loose it for convenience.
disallow_subclassing_any = true    # Default `--strict` mode.
disallow_untyped_calls = false     # Default `--strict` mode. Loose it for convenience.
disallow_untyped_decorators = true # Default `--strict` mode.
disallow_untyped_defs = false      # Default `--strict` mode. Loose it for convenience.
ignore_missing_imports = true      # Used libraries are not fully annotated. Loose it for convenience.
no_implicit_optional = true        # Default `--strict` mode.
no_implicit_reexport = false       # Default `--strict` mode. Loose it for convenience.
show_error_codes = true            # Richer report.
show_error_context = true          # Richer report.
strict_equality = true             # Default `--strict` mode.
warn_redundant_casts = true        # Default `--strict` mode.
warn_return_any = true             # Default `--strict` mode.
warn_unreachable = true            # More strict mode.
warn_unused_configs = true         # Default `--strict` mode.
warn_unused_ignores = true         # Default `--strict` mode.
```
When I run mypy, it gives following message:
```bash
error: Class cannot subclass "InMemoryDataset" (has type "Any")  [misc]
```
I think the reason is pytorch geometric dataset is a subclass of torch dataset which has a generic type variable.
Please update in future.
Thanks.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11
* OS: Linux
* Python version: 3.9
* CUDA/cuDNN version: 11.5
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
