### ISSUE TITLE
GraphGym

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#5132]
### 🚀 The feature, motivation and pitch

The overall goal of this roadmap is to ensure a tighter connection between PyG core and the GraphGym configuration manager. Furthermore, an additional goal is to not re-invent the wheel in GraphGym and make use of popular open-source frameworks whenever applicable, *e.g.*, for configuration managament, training, logging, and autoML.

As such, this roadmap structures itself into different components such as **general improvements** (*e.g.*, tighter connection between Pyg and GraphGym), [**PyTorch Lightning integration**](https://www.pytorchlightning.ai/), and [**Hydra integration**](https://hydra.cc/) as our configuration tool.

### General Roadmap

* [ ] Add `register` functionality to models in PyG core
* [ ] Remove any layer/model definition of GraphGym and move it to PyG core
* [ ] Expose a `graphgym` bash script in a `bin/` folder - GraphGym usage should not require manually cloning of PyG
* [ ] ...

### PyTorch Lightning Integration

[GraphGym](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/graphgym/train.py) training experience can be improved for scalability, mixed precision support, logging and checkpoints with [PyTorch Lightning](https://github.com/PyTorchLightning/pytorch-lightning) integration.

* [x] Write [`LightningModule`](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html)
* [ ] Refactor `load_ckpt` and `save_ckpt` with PL checkpoint save and load method
* [x] Update [train](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/graphgym/train.py#L56) method with PL `Trainer` and the `LightningModule` implementation
* [ ] Integrate `LightningDataset`, `LightningNodeData` and `LightningLinkData` modules
* [ ] ...

### Hydra Integration

Users of PyG should be able to write GraphGym configurations by being able to make full use of PyG functionality. In particular, we want to allow access to *any* dataset, *any* data transformation pipeline, and *any* GNN layer/model. For this, we need to follow a structured/composable configuration, *e.g.*, as introduced [here](https://github.com/pyg-team/pytorch_geometric/blob/master/test/graphgym/my_config.yaml)

```
defaults:
  - dataset: KarateClub
  - transform@dataset.transform:
      - NormalizeFeatures
      - AddSelfLoops
  - model: GCN
  - optimizer: Adam
  - lr_scheduler: ReduceLROnPlateau
  - _self_

model:
  in_channels: 34
  out_channels: 4
  hidden_channels: 16
  num_layers: 2
```

- [ ] Use variable interpolation, e.g., `model.in_channels = ${dataset.num_features}` and `model.out_channels = ${dataset.num_classes}`
* [ ] ...

### Weights & Biases Integration (TBD)

* [ ] ...

### AutoML (TBD)

* [ ] ...
